name: flutter_playground
description: A new Flutter project.

dependencies:
  cupertino_icons: ^0.1.0
  scoped_model: ^0.2.0
  local_auth: ^0.2.0
  device_info: ^0.2.0
  flutter_local_notifications: ^0.2.2
  geolocation: ^0.2.1
  google_maps_webservice: ^0.0.4
  redux: ^3.0.0
  redux_thunk: ^0.2.0
  flutter_redux: ^0.5.0
  json_annotation: ^0.2.3
 

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

